### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by kmwhite** [bensnyde/py-solusvm-api#4]
Is there a license to this? I'm implementing a JS library to use with [blessed-contrib](https://github.com/yaronn/blessed-contrib) for our Solus-HUD and wanted to base it on this code. Are there any restrictions to it's usage?

**Comment by bensnyde** [comment]
Hey Kristofer,

No restrictions!

I wouldn't turn down any credit though.

Enjoy!

**Comment by kmwhite** [comment]
Thanks! I'll be sure to give credit :+1:
